name: "ga-dtfy"
description: "Easily scan your assets with Detectify before shipping to production."
branding:
  icon: 'shield'
  color: 'orange'
inputs:
  api_key:
    description: "Your Detectify.com API key"
    required: true
  scan_profile_token:
    description: "Add your scan profile token here, as it is needed for automatically triggering the scan during the deployment"
    required: True
outputs:
  result:
    description: "Any output from Detectify's public API will be returned here"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.scan_profile_token }}
